# Generated by Django 6.0.2 on 2026-02-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['order'], 'verbose_name': 'Main category', 'verbose_name_plural': 'Main categories'},
        ),
    ]
