# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_maincategory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maincategory",
            name="main_category_image",
        ),
    ]

