# Generated by Django 6.0.2 on 2026-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_maincategory_main_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='main_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/main/'),
        ),
    ]
