# Generated by Django 6.0.2 on 2026-02-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_maincategory_options'),
        ('sizemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brands')),
                ('brand_images', models.ImageField(blank=True, null=True, upload_to='brand_images')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['is_active', 'is_popular'], name='store_brand_is_acti_9dc8a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_detailed_name', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('sku', models.CharField(blank=True, editable=False, help_text='Auto-generated Stock Keeping Unit', max_length=50, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('topwear', 'Topwear'), ('bottomwear', 'Bottomwear'), ('footwear', 'Footwear'), ('accessories', 'Accessories')], default='topwear', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category')),
                ('product_main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.maincategory')),
                ('product_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.subcategory')),
                ('size_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sizemanager.sizegroup')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_phone', models.CharField(max_length=15)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('license', models.CharField(max_length=50, unique=True)),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin must verify seller')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['business_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.seller'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_display', models.CharField(blank=True, help_text="Measurement in inches/cm (e.g'Chest:38-40 inches' or 'Length: 27 inches')", max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, editable=False, help_text='Variant SKU', max_length=50, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price difference from base product (e.g., +50 for XL)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='sizemanager.size')),
            ],
            options={
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['size'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='store_produ_product_cd7aec_idx')],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='store_produ_is_acti_23b747_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='store_produ_sku_8a55cb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='store_produ_product_bbe41e_idx'),
        ),
    ]
