# Generated by Django 5.2.11 on 2026-02-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_in_all_main_categories',
            field=models.BooleanField(default=False, help_text='If enabled, this brand appears in all main category store pages.'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['show_in_all_main_categories'], name='store_brand_show_in_315333_idx'),
        ),
    ]
