# Generated by Django 6.0.2 on 2026-02-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_show_in_all_main_categories_alter_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='store_brand_show_in_315333_idx',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='show_in_all_main_categories',
        ),
    ]
