# Generated by Django 6.0.2 on 2026-02-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hero banner title', max_length=50)),
                ('desktop_image', models.ImageField(help_text='Recommended size: 1920x800px', upload_to='hero_images/desktop')),
                ('mobile_image', models.ImageField(help_text='Recommended size: 1920x800px', upload_to='hero_images/mobile')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero banner',
                'verbose_name_plural': 'Hero banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='design_hero_is_acti_830988_idx')],
            },
        ),
    ]
