# Generated by Django 6.0.2 on 2026-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='mobile_image',
            field=models.ImageField(help_text='Recommended size: 768x600px', upload_to='hero_images/mobile'),
        ),
    ]
