# Generated by Django 5.2.11 on 2026-02-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_maincategory_options'),
        ('design', '0002_alter_hero_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('desktop_image', models.ImageField(help_text='Recommended size: 1920x700px', upload_to='main_category_banners/desktop')),
                ('mobile_image', models.ImageField(blank=True, help_text='Recommended size: 768x500px', null=True, upload_to='main_category_banners/mobile')),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(help_text='Select the main category for this banner', on_delete=django.db.models.deletion.CASCADE, related_name='design_banners', to='category.maincategory')),
            ],
            options={
                'verbose_name': 'Main category banner',
                'verbose_name_plural': 'Main category banners',
                'ordering': ['main_category__order', 'order', '-created_at'],
                'indexes': [models.Index(fields=['main_category', 'is_active', 'order'], name='design_main_main_ca_c86945_idx')],
            },
        ),
    ]
