# Generated by Django 6.0.2 on 2026-02-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_hero_id_maincategorybanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategorybanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
