# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0004_alter_maincategorybanner_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maincategorybanner",
            name="mobile_image",
        ),
    ]

