# Generated by Django 6.0.2 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0005_remove_maincategorybanner_mobile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCategoryBannerImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(help_text="Recommended size: 1920x700px", upload_to="main_category_banners/images")),
                ("title", models.CharField(blank=True, max_length=80)),
                ("subtitle", models.CharField(blank=True, max_length=120)),
                ("link", models.URLField(blank=True, max_length=200, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("banner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="design.maincategorybanner")),
            ],
            options={
                "verbose_name": "Main category banner image",
                "verbose_name_plural": "Main category banner images",
                "ordering": ["order", "-created_at"],
                "indexes": [models.Index(fields=["banner", "is_active", "order"], name="design_main_banner__e31ea4_idx")],
            },
        ),
    ]

