# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0006_maincategorybannerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maincategorybanner",
            name="desktop_image",
            field=models.ImageField(
                blank=True,
                null=True,
                help_text="Recommended size: 1920x700px",
                upload_to="main_category_banners/desktop",
            ),
        ),
    ]

