# Generated by Django 6.0.2 on 2026-02-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_alter_maincategorybanner_desktop_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maincategorybanner',
            name='design_main_main_ca_c86945_idx',
        ),
        migrations.RemoveIndex(
            model_name='maincategorybannerimage',
            name='design_main_banner__e31ea4_idx',
        ),
        migrations.RemoveField(
            model_name='maincategorybannerimage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='MainCategoryBanner',
        ),
        migrations.DeleteModel(
            name='MainCategoryBannerImage',
        ),
    ]
