# Generated by Django 6.0.2 on 2026-02-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_maincategory_main_category_image'),
        ('design', '0008_remove_maincategorybanner_design_main_main_ca_c86945_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='desktop_image',
            field=models.ImageField(help_text='Recommended size: 1920x540px', upload_to='hero_images/desktop'),
        ),
        migrations.CreateModel(
            name='MainCategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.maincategory')),
            ],
            options={
                'verbose_name': 'Main category banner',
                'verbose_name_plural': 'Main category banners',
                'ordering': ['order', 'main_category__name'],
            },
        ),
        migrations.CreateModel(
            name='MainCategoryBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 1920x540px', upload_to='banner_images')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='design.maincategorybanner')),
            ],
            options={
                'verbose_name': 'Main category banner image',
                'verbose_name_plural': 'Main category banner images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['banner', 'is_active', 'order'], name='design_main_banner__72d66d_idx')],
            },
        ),
    ]
